'use strict';

Entry.Pio = {
    id: '2.20',
    name: 'pio',
    url: 'http://www.robomation.net',
    imageName: 'pio.png',
    title: {
        ko: '삐오',
        en: 'Pio',
        jp: 'ピオ',
        vn: 'Pio',
    },
    setZero() {
        Entry.Robomation.setZero();
    },
    afterReceive(pd) {
        Entry.Robomation.afterReceive(pd, false);
        const robot = Entry.Robomation.getRobot('pio', 0);
        if (robot && robot.hasButtonEvent && robot.hasButtonEvent()) {
            Entry.engine.fireEvent('pioWhenButtonState');
        }
    },
    afterSend(sq) {
        Entry.Robomation.afterSend(sq);
    },
    getRobot() {
        const robot = Entry.Robomation.getRobot('pio', 0);
        if (robot) {
            robot.setMotoring(Entry.hw.sendQueue);
        }
        return robot;
    },
    monitorTemplate: {
        imgPath: 'hw/pio.png',
        width: 256,
        height: 256,
        listPorts: {
            signalStrength: {
                name: Lang.Blocks.pio_sensor_signal_strength,
                type: 'input',
                pos: { x: 0, y: 0 },
            },
            batteryState: {
                name: Lang.Blocks.pio_sensor_battery,
                type: 'input',
                pos: { x: 0, y: 0 },
            },
            leftWheel: {
                name: Lang.Hw.leftWheel,
                type: 'output',
                pos: { x: 0, y: 0 },
            },
            rightWheel: {
                name: Lang.Hw.rightWheel,
                type: 'output',
                pos: { x: 0, y: 0 },
            },
            buzzer: {
                name: Lang.Hw.buzzer,
                type: 'output',
                pos: { x: 0, y: 0 },
            },
        },
        ports: {},
        mode: 'both',
    },
};

Entry.Pio.setLanguage = () => ({
    ko: {
        template: {
            pio_board_move: '말판 %1 한 칸 이동하기 %2',
            pio_board_turn: '말판 %1 으로 한 번 돌기 %2',
            pio_move_forward: '앞으로 이동하기 %1',
            pio_move_backward: '뒤로 이동하기 %1',
            pio_turn: '%1 으로 돌기 %2',
            pio_move_forward_unit: '앞으로 %1 %2 이동하기 %3',
            pio_move_backward_unit: '뒤로 %1 %2 이동하기 %3',
            pio_turn_unit_in_place: '%1 으로 %2 %3 제자리 돌기 %4',
            pio_pivot_unit: '%1 바퀴 중심으로 %2 %3 %4 방향으로 돌기 %5',
            pio_change_wheels: '왼쪽 바퀴 %1 오른쪽 바퀴 %2 만큼 바꾸기 %3',
            pio_set_wheels: '왼쪽 바퀴 %1 오른쪽 바퀴 %2 (으)로 정하기 %3',
            pio_change_wheel: '%1 바퀴 %2 만큼 바꾸기 %3',
            pio_set_wheel: '%1 바퀴 %2 (으)로 정하기 %3',
            pio_stop: '정지하기 %1',
            pio_turbo_mode: '터보 모드 %1 %2',
            pio_is_wheel_moving: '바퀴 움직이는 중인가?',
            pio_rotate_neck: '목을 %1 으로 %2 도 회전하기 %3',
            pio_set_neck_speed: '목 속도를 %1 (으)로 정하기 %2',
            pio_stop_neck: '목 정지하기 %1',
            pio_is_neck_moving: '목 움직이는 중인가?',
            pio_set_eye_color: '%1 눈을 %2 으로 정하기 %3',
            pio_set_eye_color_picker: '%1 눈을 %2 로 정하기 %3',
            pio_change_eye_rgb: '%1 눈을 R: %2 G: %3 B: %4 만큼 바꾸기 %5',
            pio_set_eye_rgb: '%1 눈을 R: %2 G: %3 B: %4 (으)로 정하기 %5',
            pio_clear_eye: '%1 눈 끄기 %2',
            pio_play_sound: '%1 소리 재생하기 %2',
            pio_play_sound_times: '%1 소리 %2 번 재생하기 %3',
            pio_play_sound_until: '%1 소리 %2 번 재생하고 기다리기 %3',
            pio_change_buzzer: '버저 음을 %1 만큼 바꾸기 %2',
            pio_set_buzzer: '버저 음을 %1 (으)로 정하기 %2',
            pio_clear_sound: '소리 끄기 %1',
            pio_play_note: '%1 %2 음을 연주하기 %3',
            pio_play_note_beat: '%1 %2 음을 %3 박자 연주하기 %4',
            pio_rest_beat: '%1 박자 쉬기 %2',
            pio_change_tempo: '연주 속도를 %1 만큼 바꾸기 %2',
            pio_set_tempo: '연주 속도를 %1 BPM으로 정하기 %2',
            pio_is_sound_playing: '소리 내는 중인가?',
            pio_button: '%1 버튼',
            pio_signal_strength: '신호 세기',
            pio_when_button_state: '%1 %2 버튼을 %3 때',
            pio_button_state: '%1 버튼을 %2?',
            pio_battery_state: '배터리 %1?',
        },
        Blocks: {
            pio_forward: '앞으로',
            pio_backward: '뒤로',
            pio_leftward: '왼쪽으로',
            pio_rightward: '오른쪽으로',
            pio_left: '왼쪽',
            pio_right: '오른쪽',
            pio_both: '양쪽',
            pio_toward_forward: '앞쪽',
            pio_toward_backward: '뒤쪽',
            pio_on: '켜기',
            pio_off: '끄기',
            pio_unit_cm: 'cm',
            pio_unit_degrees: '도',
            pio_unit_seconds: '초',
            pio_unit_pulses: '펄스',
            pio_color_red: '빨간색',
            pio_color_orange: '주황색',
            pio_color_yellow: '노란색',
            pio_color_green: '초록색',
            pio_color_sky_blue: '하늘색',
            pio_color_blue: '파란색',
            pio_color_violet: '보라색',
            pio_color_purple: '자주색',
            pio_color_white: '하얀색',
            pio_sound_beep: '삐',
            pio_sound_random_beep: '무작위 삐',
            pio_sound_noise: '지지직',
            pio_sound_siren: '사이렌',
            pio_sound_engine: '엔진',
            pio_sound_chop: '쩝',
            pio_sound_robot: '로봇',
            pio_sound_dibidibidip: '디비디비딥',
            pio_sound_good_job: '잘 했어요',
            pio_sound_random_melody: '무작위 멜로디',
            pio_sound_poo: '응가',
            pio_sound_happy: '행복',
            pio_sound_angry: '화남',
            pio_sound_sad: '슬픔',
            pio_sound_sleep: '졸림',
            pio_sound_march: '행진',
            pio_sound_birthday: '생일',
            pio_sound_bath: '목욕',
            pio_note_c: '도',
            pio_note_cs: '도♯ (레♭)',
            pio_note_d: '레',
            pio_note_ds: '레♯ (미♭)',
            pio_note_e: '미',
            pio_note_f: '파',
            pio_note_fs: '파♯ (솔♭)',
            pio_note_g: '솔',
            pio_note_gs: '솔♯ (라♭)',
            pio_note_a: '라',
            pio_note_as: '라♯ (시♭)',
            pio_note_b: '시',
            pio_button_move_forward: '앞으로 가기',
            pio_button_move_backward: '뒤로 가기',
            pio_button_move_left: '왼쪽으로 가기',
            pio_button_move_right: '오른쪽으로 가기',
            pio_button_run: '실행하기',
            pio_button_behavior: '행동하기',
            pio_button_repeat: '반복하기',
            pio_button_clear: '삭제하기',
            pio_state_pressed: '눌렀을',
            pio_state_released: '떼었을',
            pio_state_clicked: '클릭했을',
            pio_state_long_pressed: '오래 눌렀을',
            pio_bstate_pressed: '눌렀는가',
            pio_bstate_released: '떼었는가',
            pio_bstate_clicked: '클릭했는가',
            pio_bstate_long_pressed: '오래 눌렀는가',
            pio_battery_normal: '정상',
            pio_battery_middle: '중간',
            pio_battery_low: '부족',
            pio_battery_empty: '없음',
            pio_sensor_signal_strength: '신호 세기',
            pio_sensor_battery: '배터리',
        },
        Helper: {
            pio_board_move: '말판 위에서 앞/뒤/왼쪽/오른쪽으로 한 칸 이동합니다.',
            pio_board_turn: '말판 위에서 왼쪽/오른쪽 방향으로 제자리에서 90도 회전합니다.',
            pio_move_forward: '앞으로 10cm 이동합니다.',
            pio_move_backward: '뒤로 10cm 이동합니다.',
            pio_turn: '왼쪽/오른쪽 방향으로 제자리에서 90도 회전합니다.',
            pio_move_forward_unit: '입력한 거리(cm)/시간(초)/펄스만큼 앞으로 이동합니다.',
            pio_move_backward_unit: '입력한 거리(cm)/시간(초)/펄스만큼 뒤로 이동합니다.',
            pio_turn_unit_in_place: '입력한 각도(도)/시간(초)/펄스만큼 왼쪽/오른쪽으로 제자리에서 회전합니다.',
            pio_pivot_unit: '왼쪽/오른쪽 바퀴를 중심으로 입력한 각도(도)/시간(초)/펄스만큼 앞쪽/뒤쪽 방향으로 회전합니다.',
            pio_change_wheels: '왼쪽/오른쪽 바퀴의 현재 속도 값에 입력한 값을 각각 더합니다.',
            pio_set_wheels: '왼쪽/오른쪽 바퀴의 속도를 입력한 값으로 각각 정합니다.',
            pio_change_wheel: '왼쪽/오른쪽/양쪽 바퀴의 현재 속도 값에 입력한 값을 더합니다.',
            pio_set_wheel: '왼쪽/오른쪽/양쪽 바퀴의 속도를 입력한 값으로 정합니다.',
            pio_stop: '양쪽 바퀴를 정지합니다.',
            pio_turbo_mode: '터보 모드를 켜거나 끕니다.',
            pio_is_wheel_moving: '바퀴가 움직이고 있으면 참으로 판단합니다.',
            pio_rotate_neck: '목을 왼쪽/오른쪽으로 입력한 각도만큼 회전합니다.',
            pio_set_neck_speed: '목 회전 속도를 입력한 단계로 정합니다.',
            pio_stop_neck: '목을 정지합니다.',
            pio_is_neck_moving: '목이 움직이고 있으면 참으로 판단합니다.',
            pio_set_eye_color: '왼쪽/오른쪽/양쪽 눈의 색을 선택한 색으로 정합니다.',
            pio_set_eye_color_picker: '왼쪽/오른쪽/양쪽 눈의 색을 색상판에서 고른 색으로 정합니다.',
            pio_change_eye_rgb: '왼쪽/오른쪽/양쪽 눈의 R/G/B 값에 입력한 값을 각각 더합니다.',
            pio_set_eye_rgb: '왼쪽/오른쪽/양쪽 눈의 R/G/B 값을 입력한 값으로 정합니다.',
            pio_clear_eye: '왼쪽/오른쪽/양쪽 눈을 끕니다.',
            pio_play_sound: '선택한 소리를 재생합니다.',
            pio_play_sound_times: '선택한 소리를 입력한 횟수만큼 재생합니다.',
            pio_play_sound_until: '선택한 소리를 입력한 횟수만큼 재생하고, 끝날 때까지 기다립니다.',
            pio_change_buzzer: '버저 음(Hz)에 입력한 값을 더합니다.',
            pio_set_buzzer: '버저 음(Hz)을 입력한 값으로 정합니다.',
            pio_clear_sound: '재생 중인 소리와 버저를 끕니다.',
            pio_play_note: '선택한 음과 옥타브의 음을 연주합니다.',
            pio_play_note_beat: '선택한 음과 옥타브의 음을 입력한 박자만큼 연주합니다.',
            pio_rest_beat: '입력한 박자만큼 쉽니다.',
            pio_change_tempo: '연주 속도(BPM)에 입력한 값을 더합니다.',
            pio_set_tempo: '연주 속도(BPM)를 입력한 값으로 정합니다.',
            pio_is_sound_playing: '소리나 음을 내고 있으면 참으로 판단합니다.',
            pio_button: '선택한 버튼의 상태 값(0 또는 1)입니다.',
            pio_signal_strength: '블루투스 무선 통신의 신호 세기입니다.',
            pio_when_button_state: '선택한 버튼을 누름/뗌/클릭/길게 누름 했을 때 아래에 연결된 블록들을 실행합니다.',
            pio_button_state: '선택한 버튼이 눌림/뗌/클릭/길게 누름 상태이면 참으로 판단합니다.',
            pio_battery_state: '배터리 잔량이 선택한 상태이면 참으로 판단합니다.',
        },
        Msgs: {
            pio_value_out_of_range_title: '삐오: 값이 범위를 벗어났습니다',
            pio_value_out_of_range:
                '입력한 값이 사용할 수 있는 범위(%1)를 벗어나 %2(으)로 조정되었습니다.',
            pio_neck_angle_too_large_title: '삐오: 목을 그만큼 돌릴 수 없습니다',
            pio_neck_angle_too_large: '입력한 각도가 너무 큽니다. 값을 줄여 주세요.',
            pio_delay_too_long_title: '삐오: 기다리는 시간이 너무 깁니다',
            pio_delay_too_long: '입력한 값만큼 기다릴 수 없어 최대 시간으로 조정되었습니다. 값을 줄여 주세요.',
        },
    },
    en: {
        template: {
            pio_board_move: 'move %1 once on board %2',
            pio_board_turn: 'turn %1 once on board %2',
            pio_move_forward: 'move forward %1',
            pio_move_backward: 'move backward %1',
            pio_turn: 'turn %1 %2',
            pio_move_forward_unit: 'move forward %1 %2 %3',
            pio_move_backward_unit: 'move backward %1 %2 %3',
            pio_turn_unit_in_place: 'turn %1 %2 %3 in place %4',
            pio_pivot_unit: 'pivot around %1 wheel %2 %3 in %4 direction %5',
            pio_change_wheels: 'change wheels by left: %1 right: %2 %3',
            pio_set_wheels: 'set wheels to left: %1 right: %2 %3',
            pio_change_wheel: 'change %1 wheel by %2 %3',
            pio_set_wheel: 'set %1 wheel to %2 %3',
            pio_stop: 'stop %1',
            pio_turbo_mode: 'turn %1 turbo mode %2',
            pio_is_wheel_moving: 'wheel moving?',
            pio_rotate_neck: 'rotate neck to %1 %2 degrees %3',
            pio_set_neck_speed: 'set neck speed to %1 %2',
            pio_stop_neck: 'stop neck %1',
            pio_is_neck_moving: 'neck moving?',
            pio_set_eye_color: 'set %1 eye to %2 %3',
            pio_set_eye_color_picker: 'set %1 eye to %2 %3',
            pio_change_eye_rgb: 'change %1 eye by r: %2 g: %3 b: %4 %5',
            pio_set_eye_rgb: 'set %1 eye to r: %2 g: %3 b: %4 %5',
            pio_clear_eye: 'clear %1 eye %2',
            pio_play_sound: 'play sound %1 %2',
            pio_play_sound_times: 'play sound %1 %2 times %3',
            pio_play_sound_until: 'play sound %1 %2 times until done %3',
            pio_change_buzzer: 'change buzzer by %1 %2',
            pio_set_buzzer: 'set buzzer to %1 %2',
            pio_clear_sound: 'clear sound %1',
            pio_play_note: 'play note %1 %2 %3',
            pio_play_note_beat: 'play note %1 %2 for %3 beats %4',
            pio_rest_beat: 'rest for %1 beats %2',
            pio_change_tempo: 'change tempo by %1 %2',
            pio_set_tempo: 'set tempo to %1 bpm %2',
            pio_is_sound_playing: 'sound playing?',
            pio_button: '%1 button',
            pio_signal_strength: 'signal strength',
            pio_when_button_state: '%1 when %2 button %3',
            pio_button_state: '%1 button %2?',
            pio_battery_state: 'battery %1?',
        },
        Blocks: {
            pio_forward: 'forward',
            pio_backward: 'backward',
            pio_leftward: 'left',
            pio_rightward: 'right',
            pio_left: 'left',
            pio_right: 'right',
            pio_both: 'both',
            pio_toward_forward: 'forward',
            pio_toward_backward: 'backward',
            pio_on: 'on',
            pio_off: 'off',
            pio_unit_cm: 'cm',
            pio_unit_degrees: 'degrees',
            pio_unit_seconds: 'seconds',
            pio_unit_pulses: 'pulses',
            pio_color_red: 'red',
            pio_color_orange: 'orange',
            pio_color_yellow: 'yellow',
            pio_color_green: 'green',
            pio_color_sky_blue: 'sky blue',
            pio_color_blue: 'blue',
            pio_color_violet: 'violet',
            pio_color_purple: 'purple',
            pio_color_white: 'white',
            pio_sound_beep: 'beep',
            pio_sound_random_beep: 'random beep',
            pio_sound_noise: 'noise',
            pio_sound_siren: 'siren',
            pio_sound_engine: 'engine',
            pio_sound_chop: 'chop',
            pio_sound_robot: 'robot',
            pio_sound_dibidibidip: 'dibidibidip',
            pio_sound_good_job: 'good job',
            pio_sound_random_melody: 'random melody',
            pio_sound_poo: 'poo',
            pio_sound_happy: 'happy',
            pio_sound_angry: 'angry',
            pio_sound_sad: 'sad',
            pio_sound_sleep: 'sleep',
            pio_sound_march: 'march',
            pio_sound_birthday: 'birthday',
            pio_sound_bath: 'bath',
            pio_note_c: 'C',
            pio_note_cs: 'C♯ (D♭)',
            pio_note_d: 'D',
            pio_note_ds: 'D♯ (E♭)',
            pio_note_e: 'E',
            pio_note_f: 'F',
            pio_note_fs: 'F♯ (G♭)',
            pio_note_g: 'G',
            pio_note_gs: 'G♯ (A♭)',
            pio_note_a: 'A',
            pio_note_as: 'A♯ (B♭)',
            pio_note_b: 'B',
            pio_button_move_forward: 'move forward',
            pio_button_move_backward: 'move backward',
            pio_button_move_left: 'move left',
            pio_button_move_right: 'move right',
            pio_button_run: 'run',
            pio_button_behavior: 'behavior',
            pio_button_repeat: 'repeat',
            pio_button_clear: 'clear',
            pio_state_pressed: 'pressed',
            pio_state_released: 'released',
            pio_state_clicked: 'clicked',
            pio_state_long_pressed: 'long-pressed',
            pio_bstate_pressed: 'pressed',
            pio_bstate_released: 'released',
            pio_bstate_clicked: 'clicked',
            pio_bstate_long_pressed: 'long-pressed',
            pio_battery_normal: 'normal',
            pio_battery_middle: 'middle',
            pio_battery_low: 'low',
            pio_battery_empty: 'empty',
            pio_sensor_signal_strength: 'signal strength',
            pio_sensor_battery: 'battery',
        },
        Helper: {
            pio_board_move: 'Moves one space forward/backward/left/right on the board.',
            pio_board_turn: 'Turns left/right 90 degrees in place on the board.',
            pio_move_forward: 'Moves forward 10 cm.',
            pio_move_backward: 'Moves backward 10 cm.',
            pio_turn: 'Turns left/right 90 degrees in place.',
            pio_move_forward_unit: 'Moves forward for the number of cm/seconds/pulses entered.',
            pio_move_backward_unit: 'Moves backward for the number of cm/seconds/pulses entered.',
            pio_turn_unit_in_place:
                'Turns left/right in place for the number of degrees/seconds/pulses entered.',
            pio_pivot_unit:
                'Pivots around the left/right wheel in the forward/backward direction for the number of degrees/seconds/pulses entered.',
            pio_change_wheels:
                'Adds the entered values to the current speed values of the left and right wheels respectively.',
            pio_set_wheels:
                'Sets the speed of the left and right wheels to the entered values respectively.',
            pio_change_wheel:
                'Adds the entered value to the current speed value of the left/right/both wheels.',
            pio_set_wheel: 'Sets the speed of the left/right/both wheels to the entered value.',
            pio_stop: 'Stops both wheels.',
            pio_turbo_mode: 'Turns turbo mode on or off.',
            pio_is_wheel_moving: 'If the wheels are moving, true, otherwise false',
            pio_rotate_neck: 'Rotates the neck left/right by the entered angle.',
            pio_set_neck_speed: 'Sets the neck rotation speed to the entered level.',
            pio_stop_neck: 'Stops the neck.',
            pio_is_neck_moving: 'If the neck is moving, true, otherwise false',
            pio_set_eye_color: 'Turns the left/right/both eyes to the selected color.',
            pio_set_eye_color_picker:
                'Turns the left/right/both eyes to the color chosen from the color palette.',
            pio_change_eye_rgb:
                'Adds the entered values to the R/G/B values of the left/right/both eyes respectively.',
            pio_set_eye_rgb:
                'Sets the R/G/B values of the left/right/both eyes to the entered values.',
            pio_clear_eye: 'Turns off the left/right/both eyes.',
            pio_play_sound: 'Plays the selected sound.',
            pio_play_sound_times: 'Plays the selected sound as many times as entered.',
            pio_play_sound_until:
                'Plays the selected sound as many times as entered, and waits for completion.',
            pio_change_buzzer:
                'Adds the entered value to the current pitch (Hz) of the buzzer sound.',
            pio_set_buzzer: 'Sets the pitch of the buzzer sound to the entered value (Hz).',
            pio_clear_sound: 'Turns off the playing sound and the buzzer.',
            pio_play_note: 'It sounds the selected tone and octave.',
            pio_play_note_beat:
                'It sounds the selected tone and octave as much as the beat you entered.',
            pio_rest_beat: 'Rests as much as the beat you entered.',
            pio_change_tempo:
                'Adds the entered value to the current BPM (beats per minute) of the playing speed.',
            pio_set_tempo: 'Sets the playing speed to the entered BPM (beats per minute).',
            pio_is_sound_playing: 'If a sound or note is playing, true, otherwise false',
            pio_button: 'The state value (0 or 1) of the selected button.',
            pio_signal_strength: 'The signal strength of the Bluetooth wireless communication.',
            pio_when_button_state:
                'When the selected button is pressed/released/clicked/long-pressed, runs the blocks connected below.',
            pio_button_state:
                'If the selected button is in the pressed/released/clicked/long-pressed state, true, otherwise false',
            pio_battery_state:
                'If the battery level is in the selected state, true, otherwise false',
        },
        Msgs: {
            pio_value_out_of_range_title: 'Pio: value out of range',
            pio_value_out_of_range:
                'The value you entered is outside the available range (%1), so it was adjusted to %2.',
            pio_neck_angle_too_large_title: 'Pio: the neck cannot turn that far',
            pio_neck_angle_too_large: 'The angle you entered is too large. Try a smaller value.',
            pio_delay_too_long_title: 'Pio: the wait is too long',
            pio_delay_too_long: 'The wait you asked for is longer than possible, so it was shortened. Try a smaller value.',
        },
    },
    jp: {
        template: {
            pio_board_move: 'ボード板上で %1 移動する %2',
            pio_board_turn: 'ボード板上で %1 へ回る %2',
            pio_move_forward: '前へ移動する %1',
            pio_move_backward: '後ろへ移動する %1',
            pio_turn: '%1 へ回る %2',
            pio_move_forward_unit: '前へ %1 %2 移動する %3',
            pio_move_backward_unit: '後ろへ %1 %2 移動する %3',
            pio_turn_unit_in_place: '%1 へ %2 %3 その場所で回る %4',
            pio_pivot_unit: '%1 車輪を中心に %2 %3 %4 方向へ回る %5',
            pio_change_wheels: '左車輪を %1 右車輪を %2 ずつ変える %3',
            pio_set_wheels: '左車輪を %1 右車輪を %2 にする %3',
            pio_change_wheel: '%1 車輪を %2 ずつ変える %3',
            pio_set_wheel: '%1 車輪を %2 にする %3',
            pio_stop: '停止する %1',
            pio_turbo_mode: 'ターボモードを %1 %2',
            pio_is_wheel_moving: '車輪を動かしているか?',
            pio_rotate_neck: '首を %1 へ %2 度回る %3',
            pio_set_neck_speed: '首の速さを %1 にする %2',
            pio_stop_neck: '首を停止する %1',
            pio_is_neck_moving: '首を動かしているか?',
            pio_set_eye_color: '%1 眼を %2 にする %3',
            pio_set_eye_color_picker: '%1 眼を %2 にする %3',
            pio_change_eye_rgb: '%1 眼をR: %2 G: %3 B: %4 ずつ変える %5',
            pio_set_eye_rgb: '%1 眼をR: %2 G: %3 B: %4 にする %5',
            pio_clear_eye: '%1 眼をオフにする %2',
            pio_play_sound: '%1 音を再生する %2',
            pio_play_sound_times: '%1 音を %2 回再生する %3',
            pio_play_sound_until: '%1 音を %2 回再生して待つ %3',
            pio_change_buzzer: 'ブザー音を %1 ずつ変える %2',
            pio_set_buzzer: 'ブザー音を %1 にする %2',
            pio_clear_sound: '音をオフにする %1',
            pio_play_note: '%1 %2 音を奏でる %3',
            pio_play_note_beat: '%1 %2 音を %3 拍子奏でる %4',
            pio_rest_beat: '%1 拍子止める %2',
            pio_change_tempo: '演奏の速さを %1 ずつ変える %2',
            pio_set_tempo: '演奏の速さを %1 BPMにする %2',
            pio_is_sound_playing: '音を出しているか?',
            pio_button: '%1 ボタン',
            pio_signal_strength: '信号強度',
            pio_when_button_state: '%1 %2 ボタンを %3 とき',
            pio_button_state: '%1 ボタンを %2?',
            pio_battery_state: '電池充電が %1?',
        },
        Blocks: {
            pio_forward: '前へ',
            pio_backward: '後ろへ',
            pio_leftward: '左へ',
            pio_rightward: '右へ',
            pio_left: '左',
            pio_right: '右',
            pio_both: '両方',
            pio_toward_forward: '前',
            pio_toward_backward: '後',
            pio_on: 'オン',
            pio_off: 'オフ',
            pio_unit_cm: 'cm',
            pio_unit_degrees: '度',
            pio_unit_seconds: '秒',
            pio_unit_pulses: 'パルス',
            pio_color_red: '赤色',
            pio_color_orange: '橙色',
            pio_color_yellow: '黄色',
            pio_color_green: '緑色',
            pio_color_sky_blue: '水色',
            pio_color_blue: '青色',
            pio_color_violet: '青紫色',
            pio_color_purple: '紫色',
            pio_color_white: '白色',
            pio_sound_beep: 'ビープ',
            pio_sound_random_beep: 'ランダムビープ',
            pio_sound_noise: 'ノイズ',
            pio_sound_siren: 'サイレン',
            pio_sound_engine: 'エンジン',
            pio_sound_chop: 'チョップ',
            pio_sound_robot: 'ロボット',
            pio_sound_dibidibidip: 'ディバディバディップ',
            pio_sound_good_job: 'よくできました',
            pio_sound_random_melody: 'ランダムメロディ',
            pio_sound_poo: 'うんこ',
            pio_sound_happy: '幸せ',
            pio_sound_angry: '怒り',
            pio_sound_sad: '悲しみ',
            pio_sound_sleep: '眠い',
            pio_sound_march: '行進',
            pio_sound_birthday: '誕生日',
            pio_sound_bath: 'お風呂',
            pio_note_c: 'ド',
            pio_note_cs: 'ド♯ (レ♭)',
            pio_note_d: 'レ',
            pio_note_ds: 'レ♯ (ミ♭)',
            pio_note_e: 'ミ',
            pio_note_f: 'ファ',
            pio_note_fs: 'ファ♯ (ソ♭)',
            pio_note_g: 'ソ',
            pio_note_gs: 'ソ♯ (ラ♭)',
            pio_note_a: 'ラ',
            pio_note_as: 'ラ♯ (シ♭)',
            pio_note_b: 'シ',
            pio_button_move_forward: '前へ移動',
            pio_button_move_backward: '後ろへ移動',
            pio_button_move_left: '左へ移動',
            pio_button_move_right: '右へ移動',
            pio_button_run: '実行',
            pio_button_behavior: '行動',
            pio_button_repeat: '繰り返し',
            pio_button_clear: '削除',
            pio_state_pressed: '押した',
            pio_state_released: '離した',
            pio_state_clicked: 'クリックした',
            pio_state_long_pressed: '長く押した',
            pio_bstate_pressed: '押したか',
            pio_bstate_released: '離したか',
            pio_bstate_clicked: 'クリックしたか',
            pio_bstate_long_pressed: '長く押したか',
            pio_battery_normal: '正常か',
            pio_battery_middle: '中間か',
            pio_battery_low: '不足しているか',
            pio_battery_empty: 'なくなったか',
            pio_sensor_signal_strength: '信号強度',
            pio_sensor_battery: '電池',
        },
        Msgs: {
            pio_value_out_of_range_title: 'ピオ: 値が範囲外です',
            pio_value_out_of_range:
                '入力した値が使える範囲(%1)外のため、%2 に調整されました。',
            pio_neck_angle_too_large_title: 'ピオ: 首はそこまで回せません',
            pio_neck_angle_too_large: '入力した角度が大きすぎます。値を小さくしてください。',
            pio_delay_too_long_title: 'ピオ: 待ち時間が長すぎます',
            pio_delay_too_long: '入力した分だけ待てないため、最大時間に調整されました。値を小さくしてください。',
        },
    },
    vn: {
        template: {
            pio_board_move: 'move %1 once on board %2',
            pio_board_turn: 'turn %1 once on board %2',
            pio_move_forward: 'move forward %1',
            pio_move_backward: 'move backward %1',
            pio_turn: 'turn %1 %2',
            pio_move_forward_unit: 'move forward %1 %2 %3',
            pio_move_backward_unit: 'move backward %1 %2 %3',
            pio_turn_unit_in_place: 'turn %1 %2 %3 in place %4',
            pio_pivot_unit: 'pivot around %1 wheel %2 %3 in %4 direction %5',
            pio_change_wheels: 'change wheels by left: %1 right: %2 %3',
            pio_set_wheels: 'set wheels to left: %1 right: %2 %3',
            pio_change_wheel: 'change %1 wheel by %2 %3',
            pio_set_wheel: 'set %1 wheel to %2 %3',
            pio_stop: 'stop %1',
            pio_turbo_mode: 'turn %1 turbo mode %2',
            pio_is_wheel_moving: 'wheel moving?',
            pio_rotate_neck: 'rotate neck to %1 %2 degrees %3',
            pio_set_neck_speed: 'set neck speed to %1 %2',
            pio_stop_neck: 'stop neck %1',
            pio_is_neck_moving: 'neck moving?',
            pio_set_eye_color: 'set %1 eye to %2 %3',
            pio_set_eye_color_picker: 'set %1 eye to %2 %3',
            pio_change_eye_rgb: 'change %1 eye by r: %2 g: %3 b: %4 %5',
            pio_set_eye_rgb: 'set %1 eye to r: %2 g: %3 b: %4 %5',
            pio_clear_eye: 'clear %1 eye %2',
            pio_play_sound: 'play sound %1 %2',
            pio_play_sound_times: 'play sound %1 %2 times %3',
            pio_play_sound_until: 'play sound %1 %2 times until done %3',
            pio_change_buzzer: 'change buzzer by %1 %2',
            pio_set_buzzer: 'set buzzer to %1 %2',
            pio_clear_sound: 'clear sound %1',
            pio_play_note: 'play note %1 %2 %3',
            pio_play_note_beat: 'play note %1 %2 for %3 beats %4',
            pio_rest_beat: 'rest for %1 beats %2',
            pio_change_tempo: 'change tempo by %1 %2',
            pio_set_tempo: 'set tempo to %1 bpm %2',
            pio_is_sound_playing: 'sound playing?',
            pio_button: '%1 button',
            pio_signal_strength: 'signal strength',
            pio_when_button_state: '%1 when %2 button %3',
            pio_button_state: '%1 button %2?',
            pio_battery_state: 'battery %1?',
        },
        Blocks: {
            pio_forward: 'forward',
            pio_backward: 'backward',
            pio_leftward: 'left',
            pio_rightward: 'right',
            pio_left: 'left',
            pio_right: 'right',
            pio_both: 'both',
            pio_toward_forward: 'forward',
            pio_toward_backward: 'backward',
            pio_on: 'on',
            pio_off: 'off',
            pio_unit_cm: 'cm',
            pio_unit_degrees: 'degrees',
            pio_unit_seconds: 'seconds',
            pio_unit_pulses: 'pulses',
            pio_color_red: 'red',
            pio_color_orange: 'orange',
            pio_color_yellow: 'yellow',
            pio_color_green: 'green',
            pio_color_sky_blue: 'sky blue',
            pio_color_blue: 'blue',
            pio_color_violet: 'violet',
            pio_color_purple: 'purple',
            pio_color_white: 'white',
            pio_sound_beep: 'beep',
            pio_sound_random_beep: 'random beep',
            pio_sound_noise: 'noise',
            pio_sound_siren: 'siren',
            pio_sound_engine: 'engine',
            pio_sound_chop: 'chop',
            pio_sound_robot: 'robot',
            pio_sound_dibidibidip: 'dibidibidip',
            pio_sound_good_job: 'good job',
            pio_sound_random_melody: 'random melody',
            pio_sound_poo: 'poo',
            pio_sound_happy: 'happy',
            pio_sound_angry: 'angry',
            pio_sound_sad: 'sad',
            pio_sound_sleep: 'sleep',
            pio_sound_march: 'march',
            pio_sound_birthday: 'birthday',
            pio_sound_bath: 'bath',
            pio_note_c: 'C',
            pio_note_cs: 'C♯ (D♭)',
            pio_note_d: 'D',
            pio_note_ds: 'D♯ (E♭)',
            pio_note_e: 'E',
            pio_note_f: 'F',
            pio_note_fs: 'F♯ (G♭)',
            pio_note_g: 'G',
            pio_note_gs: 'G♯ (A♭)',
            pio_note_a: 'A',
            pio_note_as: 'A♯ (B♭)',
            pio_note_b: 'B',
            pio_button_move_forward: 'move forward',
            pio_button_move_backward: 'move backward',
            pio_button_move_left: 'move left',
            pio_button_move_right: 'move right',
            pio_button_run: 'run',
            pio_button_behavior: 'behavior',
            pio_button_repeat: 'repeat',
            pio_button_clear: 'clear',
            pio_state_pressed: 'pressed',
            pio_state_released: 'released',
            pio_state_clicked: 'clicked',
            pio_state_long_pressed: 'long-pressed',
            pio_bstate_pressed: 'pressed',
            pio_bstate_released: 'released',
            pio_bstate_clicked: 'clicked',
            pio_bstate_long_pressed: 'long-pressed',
            pio_battery_normal: 'normal',
            pio_battery_middle: 'middle',
            pio_battery_low: 'low',
            pio_battery_empty: 'empty',
            pio_sensor_signal_strength: 'signal strength',
            pio_sensor_battery: 'battery',
        },
        Msgs: {
            pio_value_out_of_range_title: 'Pio: giá trị ngoài phạm vi',
            pio_value_out_of_range:
                'Giá trị bạn nhập nằm ngoài phạm vi sử dụng được (%1) nên đã được điều chỉnh thành %2.',
            pio_neck_angle_too_large_title: 'Pio: cổ không thể quay xa như vậy',
            pio_neck_angle_too_large: 'Góc bạn nhập quá lớn. Hãy thử giá trị nhỏ hơn.',
            pio_delay_too_long_title: 'Pio: thời gian chờ quá dài',
            pio_delay_too_long: 'Không thể chờ lâu như vậy nên đã rút ngắn về mức tối đa. Hãy thử giá trị nhỏ hơn.',
        },
    },
});

Entry.Pio.blockMenuBlocks = [
    'pio_board_move',
    'pio_board_turn',
    'pio_move_forward',
    'pio_move_backward',
    'pio_turn',
    'pio_move_forward_unit',
    'pio_move_backward_unit',
    'pio_turn_unit_in_place',
    'pio_pivot_unit',
    'pio_change_wheels',
    'pio_set_wheels',
    'pio_change_wheel',
    'pio_set_wheel',
    'pio_stop',
    'pio_turbo_mode',
    'pio_is_wheel_moving',
    'pio_rotate_neck',
    'pio_set_neck_speed',
    'pio_stop_neck',
    'pio_is_neck_moving',
    'pio_set_eye_color',
    'pio_set_eye_color_picker',
    'pio_change_eye_rgb',
    'pio_set_eye_rgb',
    'pio_clear_eye',
    'pio_play_sound',
    'pio_play_sound_times',
    'pio_play_sound_until',
    'pio_change_buzzer',
    'pio_set_buzzer',
    'pio_clear_sound',
    'pio_play_note',
    'pio_play_note_beat',
    'pio_rest_beat',
    'pio_change_tempo',
    'pio_set_tempo',
    'pio_is_sound_playing',
    'pio_button',
    'pio_signal_strength',
    'pio_when_button_state',
    'pio_button_state',
    'pio_battery_state',
];

Entry.Pio.getBlocks = function() {
    const HW = EntryStatic.colorSet.block.default.HARDWARE;
    const HW_LINE = EntryStatic.colorSet.block.darken.HARDWARE;
    const HW_ARROW = EntryStatic.colorSet.arrow.default.HARDWARE;

    const dropdown = (options, value) => ({
        type: 'Dropdown',
        options,
        value,
        fontSize: 11,
        bgColor: HW_LINE,
        arrowColor: HW_ARROW,
    });
    const indicator = () => ({
        type: 'Indicator',
        img: 'block_icon/hardware_icon.svg',
        size: 12,
    });
    const numberInput = () => ({
        type: 'Block',
        accept: 'string',
    });
    const text = (value) => ({
        type: 'text',
        params: [`${value}`],
    });

    const OPT_FWD_BWD_L_R = [
        [Lang.Blocks.pio_forward, 'FORWARD'],
        [Lang.Blocks.pio_backward, 'BACKWARD'],
        [Lang.Blocks.pio_leftward, 'LEFT'],
        [Lang.Blocks.pio_rightward, 'RIGHT'],
    ];
    const OPT_LEFT_RIGHT = [
        [Lang.Blocks.pio_left, 'LEFT'],
        [Lang.Blocks.pio_right, 'RIGHT'],
    ];
    const OPT_LEFT_RIGHT_BOTH = [
        [Lang.Blocks.pio_left, 'LEFT'],
        [Lang.Blocks.pio_right, 'RIGHT'],
        [Lang.Blocks.pio_both, 'BOTH'],
    ];
    const OPT_TOWARD = [
        [Lang.Blocks.pio_toward_forward, 'FORWARD'],
        [Lang.Blocks.pio_toward_backward, 'BACKWARD'],
    ];
    const OPT_ON_OFF = [
        [Lang.Blocks.pio_on, 'ON'],
        [Lang.Blocks.pio_off, 'OFF'],
    ];
    const OPT_MOVE_UNIT = [
        [Lang.Blocks.pio_unit_cm, 'CM'],
        [Lang.Blocks.pio_unit_seconds, 'SECONDS'],
        [Lang.Blocks.pio_unit_pulses, 'PULSES'],
    ];
    const OPT_TURN_UNIT = [
        [Lang.Blocks.pio_unit_degrees, 'DEGREES'],
        [Lang.Blocks.pio_unit_seconds, 'SECONDS'],
        [Lang.Blocks.pio_unit_pulses, 'PULSES'],
    ];
    const OPT_NECK_SPEED = [
        ['1', '1'],
        ['2', '2'],
        ['3', '3'],
        ['4', '4'],
        ['5', '5'],
        ['6', '6'],
    ];
    const OPT_COLOR = [
        [Lang.Blocks.pio_color_red, 'RED'],
        [Lang.Blocks.pio_color_orange, 'ORANGE'],
        [Lang.Blocks.pio_color_yellow, 'YELLOW'],
        [Lang.Blocks.pio_color_green, 'GREEN'],
        [Lang.Blocks.pio_color_sky_blue, 'SKY_BLUE'],
        [Lang.Blocks.pio_color_blue, 'BLUE'],
        [Lang.Blocks.pio_color_violet, 'VIOLET'],
        [Lang.Blocks.pio_color_purple, 'PURPLE'],
        [Lang.Blocks.pio_color_white, 'WHITE'],
    ];
    const OPT_SOUND = [
        [Lang.Blocks.pio_sound_beep, 'BEEP'],
        [Lang.Blocks.pio_sound_random_beep, 'RANDOM_BEEP'],
        [Lang.Blocks.pio_sound_noise, 'NOISE'],
        [Lang.Blocks.pio_sound_siren, 'SIREN'],
        [Lang.Blocks.pio_sound_engine, 'ENGINE'],
        [Lang.Blocks.pio_sound_chop, 'CHOP'],
        [Lang.Blocks.pio_sound_robot, 'ROBOT'],
        [Lang.Blocks.pio_sound_dibidibidip, 'DIBIDIBIDIP'],
        [Lang.Blocks.pio_sound_good_job, 'GOOD_JOB'],
        [Lang.Blocks.pio_sound_random_melody, 'RANDOM_MELODY'],
        [Lang.Blocks.pio_sound_poo, 'POO'],
        [Lang.Blocks.pio_sound_happy, 'HAPPY'],
        [Lang.Blocks.pio_sound_angry, 'ANGRY'],
        [Lang.Blocks.pio_sound_sad, 'SAD'],
        [Lang.Blocks.pio_sound_sleep, 'SLEEP'],
        [Lang.Blocks.pio_sound_march, 'MARCH'],
        [Lang.Blocks.pio_sound_birthday, 'BIRTHDAY'],
        [Lang.Blocks.pio_sound_bath, 'BATH'],
    ];
    const OPT_NOTE = [
        [Lang.Blocks.pio_note_c, 'C'],
        [Lang.Blocks.pio_note_cs, 'CS'],
        [Lang.Blocks.pio_note_d, 'D'],
        [Lang.Blocks.pio_note_ds, 'DS'],
        [Lang.Blocks.pio_note_e, 'E'],
        [Lang.Blocks.pio_note_f, 'F'],
        [Lang.Blocks.pio_note_fs, 'FS'],
        [Lang.Blocks.pio_note_g, 'G'],
        [Lang.Blocks.pio_note_gs, 'GS'],
        [Lang.Blocks.pio_note_a, 'A'],
        [Lang.Blocks.pio_note_as, 'AS'],
        [Lang.Blocks.pio_note_b, 'B'],
    ];
    const OPT_OCTAVE = [
        ['1', '1'],
        ['2', '2'],
        ['3', '3'],
        ['4', '4'],
        ['5', '5'],
        ['6', '6'],
        ['7', '7'],
    ];
    const OPT_BUTTON = [
        [Lang.Blocks.pio_button_move_forward, 'MOVE_FORWARD'],
        [Lang.Blocks.pio_button_move_backward, 'MOVE_BACKWARD'],
        [Lang.Blocks.pio_button_move_left, 'MOVE_LEFT'],
        [Lang.Blocks.pio_button_move_right, 'MOVE_RIGHT'],
        [Lang.Blocks.pio_button_run, 'RUN'],
        [Lang.Blocks.pio_button_behavior, 'BEHAVIOR'],
        [Lang.Blocks.pio_button_repeat, 'REPEAT'],
        [Lang.Blocks.pio_button_clear, 'CLEAR'],
    ];
    const OPT_WHEN_STATE = [
        [Lang.Blocks.pio_state_pressed, 'PRESSED'],
        [Lang.Blocks.pio_state_released, 'RELEASED'],
        [Lang.Blocks.pio_state_clicked, 'CLICKED'],
        [Lang.Blocks.pio_state_long_pressed, 'LONG_PRESSED'],
    ];
    const OPT_BUTTON_STATE = [
        [Lang.Blocks.pio_bstate_pressed, 'PRESSED'],
        [Lang.Blocks.pio_bstate_released, 'RELEASED'],
        [Lang.Blocks.pio_bstate_clicked, 'CLICKED'],
        [Lang.Blocks.pio_bstate_long_pressed, 'LONG_PRESSED'],
    ];
    const OPT_BATTERY = [
        [Lang.Blocks.pio_battery_normal, 'NORMAL'],
        [Lang.Blocks.pio_battery_middle, 'MIDDLE'],
        [Lang.Blocks.pio_battery_low, 'LOW'],
        [Lang.Blocks.pio_battery_empty, 'EMPTY'],
    ];

    const command = (type, params, def, paramsKeyMap, klass, method) => ({
        color: HW,
        outerLine: HW_LINE,
        skeleton: 'basic',
        statements: [],
        params,
        events: {},
        def: { params: def, type },
        paramsKeyMap,
        class: klass,
        isNotFor: ['pio'],
        func(sprite, script) {
            const robot = Entry.Pio.getRobot();
            return robot ? robot[method](script) : script;
        },
    });
    const booleanField = (type, params, def, paramsKeyMap, klass, method) => ({
        color: HW,
        outerLine: HW_LINE,
        fontColor: '#fff',
        skeleton: 'basic_boolean_field',
        statements: [],
        params,
        events: {},
        def: { params: def, type },
        paramsKeyMap,
        class: klass,
        isNotFor: ['pio'],
        func(sprite, script) {
            const robot = Entry.Pio.getRobot();
            return robot ? robot[method](script) : false;
        },
    });
    const stringField = (type, params, def, paramsKeyMap, klass, method) => ({
        color: HW,
        outerLine: HW_LINE,
        fontColor: '#fff',
        skeleton: 'basic_string_field',
        statements: [],
        params,
        events: {},
        def: { params: def, type },
        paramsKeyMap,
        class: klass,
        isNotFor: ['pio'],
        func(sprite, script) {
            const robot = Entry.Pio.getRobot();
            return robot ? robot[method](script) : 0;
        },
    });

    return {
        // -------- motion --------
        pio_board_move: command(
            'pio_board_move',
            [dropdown(OPT_FWD_BWD_L_R, 'FORWARD'), indicator()],
            [null, null],
            { DIRECTION: 0 },
            'pio_board',
            'boardMove'
        ),
        pio_board_turn: command(
            'pio_board_turn',
            [dropdown(OPT_LEFT_RIGHT, 'LEFT'), indicator()],
            [null, null],
            { DIRECTION: 0 },
            'pio_board',
            'boardTurn'
        ),
        pio_move_forward: command(
            'pio_move_forward',
            [indicator()],
            [null],
            {},
            'pio_wheel',
            'moveForward'
        ),
        pio_move_backward: command(
            'pio_move_backward',
            [indicator()],
            [null],
            {},
            'pio_wheel',
            'moveBackward'
        ),
        pio_turn: command(
            'pio_turn',
            [dropdown(OPT_LEFT_RIGHT, 'LEFT'), indicator()],
            [null, null],
            { DIRECTION: 0 },
            'pio_wheel',
            'turn'
        ),
        pio_move_forward_unit: command(
            'pio_move_forward_unit',
            [numberInput(), dropdown(OPT_MOVE_UNIT, 'CM'), indicator()],
            [text('10'), null, null],
            { VALUE: 0, UNIT: 1 },
            'pio_wheel',
            'moveForwardUnit'
        ),
        pio_move_backward_unit: command(
            'pio_move_backward_unit',
            [numberInput(), dropdown(OPT_MOVE_UNIT, 'CM'), indicator()],
            [text('10'), null, null],
            { VALUE: 0, UNIT: 1 },
            'pio_wheel',
            'moveBackwardUnit'
        ),
        pio_turn_unit_in_place: command(
            'pio_turn_unit_in_place',
            [dropdown(OPT_LEFT_RIGHT, 'LEFT'), numberInput(), dropdown(OPT_TURN_UNIT, 'DEGREES'), indicator()],
            [null, text('90'), null, null],
            { DIRECTION: 0, VALUE: 1, UNIT: 2 },
            'pio_wheel',
            'turnUnit'
        ),
        pio_pivot_unit: command(
            'pio_pivot_unit',
            [
                dropdown(OPT_LEFT_RIGHT, 'LEFT'),
                numberInput(),
                dropdown(OPT_TURN_UNIT, 'DEGREES'),
                dropdown(OPT_TOWARD, 'FORWARD'),
                indicator(),
            ],
            [null, text('90'), null, null, null],
            { WHEEL: 0, VALUE: 1, UNIT: 2, TOWARD: 3 },
            'pio_wheel',
            'pivotUnit'
        ),
        pio_change_wheels: command(
            'pio_change_wheels',
            [numberInput(), numberInput(), indicator()],
            [text('10'), text('10'), null],
            { LEFT: 0, RIGHT: 1 },
            'pio_wheel',
            'changeWheels'
        ),
        pio_set_wheels: command(
            'pio_set_wheels',
            [numberInput(), numberInput(), indicator()],
            [text('70'), text('70'), null],
            { LEFT: 0, RIGHT: 1 },
            'pio_wheel',
            'setWheels'
        ),
        pio_change_wheel: command(
            'pio_change_wheel',
            [dropdown(OPT_LEFT_RIGHT_BOTH, 'LEFT'), numberInput(), indicator()],
            [null, text('10'), null],
            { WHEEL: 0, VALUE: 1 },
            'pio_wheel',
            'changeWheel'
        ),
        pio_set_wheel: command(
            'pio_set_wheel',
            [dropdown(OPT_LEFT_RIGHT_BOTH, 'LEFT'), numberInput(), indicator()],
            [null, text('70'), null],
            { WHEEL: 0, VALUE: 1 },
            'pio_wheel',
            'setWheel'
        ),
        pio_stop: command('pio_stop', [indicator()], [null], {}, 'pio_wheel', 'stop'),
        pio_turbo_mode: command(
            'pio_turbo_mode',
            [dropdown(OPT_ON_OFF, 'OFF'), indicator()],
            [null, null],
            { MODE: 0 },
            'pio_wheel',
            'setTurboMode'
        ),
        pio_is_wheel_moving: booleanField(
            'pio_is_wheel_moving',
            [],
            [],
            {},
            'pio_wheel',
            'isWheelMoving'
        ),
        pio_rotate_neck: command(
            'pio_rotate_neck',
            [dropdown(OPT_LEFT_RIGHT, 'LEFT'), numberInput(), indicator()],
            [null, text('10'), null],
            { DIRECTION: 0, VALUE: 1 },
            'pio_neck',
            'rotateNeck'
        ),
        pio_set_neck_speed: command(
            'pio_set_neck_speed',
            [dropdown(OPT_NECK_SPEED, '4'), indicator()],
            [null, null],
            { SPEED: 0 },
            'pio_neck',
            'setNeckSpeed'
        ),
        pio_stop_neck: command('pio_stop_neck', [indicator()], [null], {}, 'pio_neck', 'stopNeck'),
        pio_is_neck_moving: booleanField(
            'pio_is_neck_moving',
            [],
            [],
            {},
            'pio_neck',
            'isNeckMoving'
        ),

        // -------- looks (eye) --------
        pio_set_eye_color: command(
            'pio_set_eye_color',
            [dropdown(OPT_LEFT_RIGHT_BOTH, 'LEFT'), dropdown(OPT_COLOR, 'RED'), indicator()],
            [null, null, null],
            { EYE: 0, COLOR: 1 },
            'pio_led',
            'setEyeColor'
        ),
        pio_set_eye_color_picker: command(
            'pio_set_eye_color_picker',
            [dropdown(OPT_LEFT_RIGHT_BOTH, 'LEFT'), { type: 'Color' }, indicator()],
            [null, null, null],
            { EYE: 0, COLOR: 1 },
            'pio_led',
            'setEyeColorPicker'
        ),
        pio_change_eye_rgb: command(
            'pio_change_eye_rgb',
            [dropdown(OPT_LEFT_RIGHT_BOTH, 'LEFT'), numberInput(), numberInput(), numberInput(), indicator()],
            [null, text('10'), text('0'), text('0'), null],
            { EYE: 0, RED: 1, GREEN: 2, BLUE: 3 },
            'pio_led',
            'changeEyeRgb'
        ),
        pio_set_eye_rgb: command(
            'pio_set_eye_rgb',
            [dropdown(OPT_LEFT_RIGHT_BOTH, 'LEFT'), numberInput(), numberInput(), numberInput(), indicator()],
            [null, text('255'), text('0'), text('0'), null],
            { EYE: 0, RED: 1, GREEN: 2, BLUE: 3 },
            'pio_led',
            'setEyeRgb'
        ),
        pio_clear_eye: command(
            'pio_clear_eye',
            [dropdown(OPT_LEFT_RIGHT_BOTH, 'LEFT'), indicator()],
            [null, null],
            { EYE: 0 },
            'pio_led',
            'clearEye'
        ),

        // -------- sound --------
        pio_play_sound: command(
            'pio_play_sound',
            [dropdown(OPT_SOUND, 'BEEP'), indicator()],
            [null, null],
            { SOUND: 0 },
            'pio_sound',
            'playSound'
        ),
        pio_play_sound_times: command(
            'pio_play_sound_times',
            [dropdown(OPT_SOUND, 'BEEP'), numberInput(), indicator()],
            [null, text('1'), null],
            { SOUND: 0, REPEAT: 1 },
            'pio_sound',
            'playSoundTimes'
        ),
        pio_play_sound_until: command(
            'pio_play_sound_until',
            [dropdown(OPT_SOUND, 'BEEP'), numberInput(), indicator()],
            [null, text('1'), null],
            { SOUND: 0, REPEAT: 1 },
            'pio_sound',
            'playSoundUntil'
        ),
        pio_change_buzzer: command(
            'pio_change_buzzer',
            [numberInput(), indicator()],
            [text('10'), null],
            { HZ: 0 },
            'pio_sound',
            'changeBuzzer'
        ),
        pio_set_buzzer: command(
            'pio_set_buzzer',
            [numberInput(), indicator()],
            [text('1000'), null],
            { HZ: 0 },
            'pio_sound',
            'setBuzzer'
        ),
        pio_clear_sound: command(
            'pio_clear_sound',
            [indicator()],
            [null],
            {},
            'pio_sound',
            'clearSound'
        ),
        pio_play_note: command(
            'pio_play_note',
            [dropdown(OPT_NOTE, 'C'), dropdown(OPT_OCTAVE, '4'), indicator()],
            [null, null, null],
            { NOTE: 0, OCTAVE: 1 },
            'pio_sound',
            'playNote'
        ),
        pio_play_note_beat: command(
            'pio_play_note_beat',
            [dropdown(OPT_NOTE, 'C'), dropdown(OPT_OCTAVE, '4'), numberInput(), indicator()],
            [null, null, text('0.5'), null],
            { NOTE: 0, OCTAVE: 1, BEAT: 2 },
            'pio_sound',
            'playNoteBeat'
        ),
        pio_rest_beat: command(
            'pio_rest_beat',
            [numberInput(), indicator()],
            [text('0.25'), null],
            { BEAT: 0 },
            'pio_sound',
            'restBeat'
        ),
        pio_change_tempo: command(
            'pio_change_tempo',
            [numberInput(), indicator()],
            [text('20'), null],
            { BPM: 0 },
            'pio_sound',
            'changeTempo'
        ),
        pio_set_tempo: command(
            'pio_set_tempo',
            [numberInput(), indicator()],
            [text('60'), null],
            { BPM: 0 },
            'pio_sound',
            'setTempo'
        ),
        pio_is_sound_playing: booleanField(
            'pio_is_sound_playing',
            [],
            [],
            {},
            'pio_sound',
            'isSoundPlaying'
        ),

        // -------- sensing --------
        pio_button: stringField(
            'pio_button',
            [dropdown(OPT_BUTTON, 'MOVE_FORWARD')],
            [null],
            { BUTTON: 0 },
            'pio_sensor',
            'getButton'
        ),
        pio_signal_strength: stringField(
            'pio_signal_strength',
            [],
            [],
            {},
            'pio_sensor',
            'getSignalStrength'
        ),
        pio_when_button_state: {
            color: HW,
            outerLine: HW_LINE,
            fontColor: '#fff',
            skeleton: 'basic_event',
            statements: [],
            params: [
                {
                    type: 'Indicator',
                    img: 'block_icon/start_icon_hardware.svg',
                    size: 14,
                    position: { x: 0, y: -2 },
                },
                dropdown(OPT_BUTTON, 'MOVE_FORWARD'),
                dropdown(OPT_WHEN_STATE, 'PRESSED'),
            ],
            events: {},
            def: {
                params: [null, null, null],
                type: 'pio_when_button_state',
            },
            paramsKeyMap: { DUMMY: 0, BUTTON: 1, STATE: 2 },
            event: 'pioWhenButtonState',
            class: 'pio_sensor',
            isNotFor: ['pio'],
            func(sprite, script) {
                const robot = Entry.Pio.getRobot();
                if (robot && robot.checkButtonState(script)) {
                    return script.callReturn();
                }
                return this.die();
            },
        },
        pio_button_state: booleanField(
            'pio_button_state',
            [dropdown(OPT_BUTTON, 'MOVE_FORWARD'), dropdown(OPT_BUTTON_STATE, 'PRESSED')],
            [null, null],
            { BUTTON: 0, STATE: 1 },
            'pio_sensor',
            'isButtonState'
        ),
        pio_battery_state: booleanField(
            'pio_battery_state',
            [dropdown(OPT_BATTERY, 'NORMAL')],
            [null],
            { BATTERY: 0 },
            'pio_sensor',
            'checkBatteryState'
        ),
    };
};

module.exports = Entry.Pio;
