name: 'release'
on:
    release:
        types: [created]

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 9
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'pnpm'
            - run: pnpm install
            - run: pnpm dist
            - uses: JS-DevTools/npm-publish@v3
              with:
                  token: ${{ secrets.NPM_TOKEN }}
